import type { Metadata } from "next";
import { Inter } from "next/font/google";
import i18nConfig from "../../../i18nConfig"
import { dir } from 'i18next';
import "./globals.css";
import Providers from "./providers";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Boilerplate Next.js with i18n",
  description: "Generated by create next app",
};
export function generateStaticParams() {
  return i18nConfig.locales.map(locale => ({ locale }));
}

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode,
  params: { locale: string },
}>) {
  return (
    <html  lang={locale} dir={dir(locale)}>
      <body className={inter.className}>
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
